### ISSUE TITLE
Log Timezone Incorrect

### ISSUE THREAD

**Issue by Cpt-Echo** [tpill90/steam-lancache-prefill#294] opened 2023-05-01 22:29 UTC
Prefill not respecting the timezone in the container for its logs when started by Cron
Timezone is defaulting to +0 UTC

Expected behaviour - Timezone is inherited from host server or can also be set with TZ environmental variable in docker run.
Both options have been tried with no success.
Other processes within the same container (e.g. Cron) do use the correct timezone.
e.g. Cron is set to 2am to start prefill, Prefill starts correctly at 2am, however logs show 4pm (correct timezone is +10 UTC)

If Prefill is started manually through command line the logs do show the correct time.
This is only a problem when process is started by Cron

Region - Australia
Platform - Docker
Discord - Cpt Echo#3755

**Comment by tpill90** [comment] 2023-05-03 02:11
I've figured out the issue with this, and it should be fixed in the next release.  Adding `-e TZ=Europe/London` as an environment variable should now override correctly.

**Comment by tpill90** [comment] 2023-05-10 23:08
Released in [v2.1.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v2.1.0)

**Comment by Cpt-Echo** [comment] 2023-05-13 00:06
Unfortunately this fix did not work. Log still defaulting to 0 UTC even with -e TZ=Australia/Sydney (+10 UTC)
As can be seen in the log screenshot, CRON is set for 2am, and executes correctly at 2am (+10utc) , however logging shows 4pm the day prior (0 UTC)

![image](https://github.com/tpill90/steam-lancache-prefill/assets/7140129/5f52e5eb-9540-4ce3-9f60-44324b794f44)

**Comment by tpill90** [comment] 2023-06-28 01:23
Ah thanks for the screenshot, I think I see whats going on here.  I made the fix in my Docker image, however you're using ich777's container which wouldn't have my fix in it.

@ich777 Could you take a look at this when you get a chance?  I'm pretty sure that this issue can be resolved by doing the same fix that I did in this PR : https://github.com/tpill90/steam-lancache-prefill/pull/296/files

**Comment by ich777** [comment] 2023-06-28 15:20
@Cpt-Echo thanks for the report but I have to say, next time please use the support thread on the Unraid forums since this is my container.

Please update the container itself, I've now added `tzdata` and it should work as intended.

**Comment by ich777** [comment] 2023-07-02 11:44
@Cpt-Echo any update on this? Does it now work?

**Comment by tpill90** [comment] 2023-07-03 17:53
I'm going to close this out, and it can be reopened if the issue persists

**Closed by tpill90** 2023-07-03 17:53 UTC
Labels: bug
