### ISSUE TITLE
Steam Prefill stops after downloading 1-2 apps

### ISSUE THREAD

**Issue by andritolion** [tpill90/steam-lancache-prefill#318] opened 2023-08-13 20:05 UTC
**Describe the bug**
Steam Prefill frequently stops after downloading 1-2 apps. Troubleshooted by removing all saved data from AppData, but no improvement found. Need to force quit with Ctrl+C to start downloading the next few apps.

**Additional Details**
 - Platform: ich777's Unraid App
 - Region: West US

**Screenshots**
<img width="585" alt="image" src="https://github.com/tpill90/steam-lancache-prefill/assets/34906030/f496fd23-f732-4ccd-a501-f8fb6492ba09">

**Comment by tpill90** [comment] 2023-08-14 01:20
Could you try running the prefill on a Windows machine and see if the same issue keeps happening?

**Comment by andritolion** [comment] 2023-08-14 16:54
Here are my Docker launch arguments.
```
docker run
  -d
  --name='LANCache-Prefill'
  --net='br0'
  -e TZ="America/Los_Angeles"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="catNAS"
  -e HOST_CONTAINERNAME="LANCache-Prefill"
  -e 'ENABLE_BN'='false'
  -e 'CRON_SCHED_BN'='0 5 * * *'
  -e 'ENABLE_EPIC'='false'
  -e 'PREFILL_PARAMS_EPIC'=''
  -e 'CRON_SCHED_EPIC'='30 4 * * *'
  -e 'ENABLE_STEAM'='true'
  -e 'PREFILL_PARAMS_STEAM'='--recent'
  -e 'CRON_SCHED_STEAM'='30 3 * * *'
  -e 'UPDATES'='true'
  -e 'PREFILL_ONSTARTUP'='false'
  -e 'LOGCLEANUP'='true'
  -e 'CRON_SCHED_GLOBAL'=''
  -e 'UID'='99'
  -e 'GID'='100'
  -e 'DATA_PERM'='770'
  -e 'UMASK'='000'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/ich777/docker-templates/master/ich777/images/prefill.png'
  -v '/mnt/user/appdata/lancache-prefill':'/lancacheprefill':'rw'
  --restart=unless-stopped
  --dns=192.168.2.10 'ich777/lancache-prefill'
```

**Comment by tpill90** [comment] 2023-08-18 19:18
@ich777 could you help out with this?

**Comment by ich777** [comment] 2023-08-18 20:20
@andritolion from what I can see everything is configured correctly.
I can't reproduce that behavior over here and it is working just fine. Does the cron schedule also do the same or is it not working there too?



> Need to force quit with Ctrl+C to start downloading the next few apps.

The container was not meant to do that directly from the command line but it should not change anything if you do it like you do it.
Have you yet considered to set `PREFILL_ONSTARTUP` to `true` and if it does the same?

**Comment by ich777** [comment] 2023-08-21 07:33
@tpill90 & @andritolion I have now verified over the weekend that the container is working as expected on my system and also on a system from another user.
On my system it automatically updated four apps in one go with the automatic update. I also tried it the next day from the command line and it also updated five apps.

@tpill90 If no further response is given I would recommend to close this issue.
@andritolion I got now a few other reports that the updates from game containers are not working sometimes properly so I think this is actually an issue with the Steam CDN in general.

**Comment by andritolion** [comment] 2023-08-21 11:09
Apologies for no update until now. Been busy the last few days. It doesn't seem like the cron schedule can completely update my library. Reproduced the issue a bit ago, same pausing after one app. I'll try and see if setting that variable to true makes an improvement.
<img width="527" alt="image" src="https://github.com/tpill90/steam-lancache-prefill/assets/34906030/6efb01f7-3cd0-4c0c-b301-137f1b47d672">

**Comment by tpill90** [comment] 2023-08-21 12:31
@andritolion What region are you in? I'm curious since sometimes it can have an effect. 

Also could you add the flag `--debug` to your prefill command and try to reproduce again? Might give us some more info

**Comment by andritolion** [comment] 2023-08-21 19:17
I am in the Los Angeles, United States region. Crashed this time, completely different cause though.
<img width="920" alt="image" src="https://github.com/tpill90/steam-lancache-prefill/assets/34906030/dc0db422-6e8e-4e94-a26d-007df9b32d6f">

**Comment by andritolion** [comment] 2023-08-21 19:18
Think I see it trying to pull a style from a local location that does not exist (your Dropbox).

**Comment by ich777** [comment] 2023-09-05 06:39
@andritolion any update on this?

**Comment by ss1gohan13** [comment] 2023-10-03 15:46
@ich777 I'm having some very _similar_ issues to @andritolion
I've made a post over in the unRAID forums as well.

**Comment by ich777** [comment] 2023-10-03 17:26
@ss1gohan13 your issue sounds more like a lancache issue itself not like a prefill issue.

I‘m also not a huge fan of posting multiple times.

**Comment by tpill90** [comment] 2023-10-09 14:46
Closing this as no additional info was given

**Closed by tpill90** 2023-10-09 14:46 UTC
Labels: bug
