### ISSUE TITLE
Unable to Authenticate with Certain Regions

### ISSUE THREAD

**Issue by am-jr** [tpill90/steam-lancache-prefill#386] opened 2024-10-05 00:36 UTC
I am experiencing an issue with the prefill script where authentication fails when attempting to connect to certain regions. Specifically, the script fails to authenticate or connect during a prefill when trying to connect to either Seattle or Los Angeles. However, Atlanta and Stockholm both worked.

**Steps to Reproduce:**

1. Run the `steam-lancache-prefill` script.
2. Attempt to authenticate or connect to either the Seattle or Los Angeles regions.
3. Observe that the script fails to authenticate.

**Expected Behavior:**

The script should successfully authenticate and connect to the specified regions without errors.

**Actual Behavior:**

The script fails to authenticate when connecting to Seattle or Los Angeles.

**Environment:**

- Operating Systems: Both Windows and Linux
- Issue started: Today

**Additional Information:**

This issue seems to be region-specific and began occurring today 2024/10/04.

**Comment by tpill90** [comment] 2024-10-10 16:09
I'm marking this as a duplicate since I believe that this is the same issue as #376.  I will leave this open for tracking purposes until the root issue is fixed.

**Comment by tpill90** [comment] 2024-11-23 22:23
Closing this out since it seems like the fix has been working as intended.

**Closed by tpill90** 2024-11-23 22:23 UTC
Labels: bug, duplicate
