### ISSUE TITLE
Unable to prefill EA titles 

### ISSUE THREAD

**Issue by dilsonn** [tpill90/steam-lancache-prefill#70] opened 2022-08-16 09:35 UTC
I've been seeing a conistent issue in trying to prefill what seems to be exclusively EA titles using this tool, they fail instantly with the following error:

```
[8:56:32 AM] Starting Burnout:tm: Paradise Remastered
   Unexpected download error : An unexpected error occured while downloading manifests!  Skipping...
```
I've noticed it on Battlefield 1, Battlefield V and many other EA titles
All other non-EA titles prefill without issue. This is also using version 1.3.0 (latest at time of writing).

**Comment by stuart-c-moore** [comment] 2022-08-18 20:52
I'm getting the same for `Sid Meier's Civilization VI`

Everything else I've tried downloads fine

**Comment by tpill90** [comment] 2022-08-18 20:57
I was able to reproduce this using  [Dirt 5](https://steamdb.info/app/1038250/info/)
 added to my account using **[EA Play](https://steamdb.info/app/1289670/)** 
 
![image](https://user-images.githubusercontent.com/766513/185492998-581c8517-be55-4db6-8059-4fac9a735563.png)

**Comment by tpill90** [comment] 2022-08-18 21:48
@dilsonn @stuart-c-moore I have a potential fix for this issue, that's been tested on my machine as resolving the issue with Dirt 5.
Could you please test out the following build and let me know if it resolves the issue? 
[SteamPrefill-1.3.0-linux-arm64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9377882/SteamPrefill-1.3.0-linux-arm64.zip)
[SteamPrefill-1.3.0-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9377885/SteamPrefill-1.3.0-linux-x64.zip)
[SteamPrefill-1.3.0-osx-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9377887/SteamPrefill-1.3.0-osx-x64.zip)
[SteamPrefill-1.3.0-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9377888/SteamPrefill-1.3.0-win-x64.zip)

**Comment by stuart-c-moore** [comment] 2022-08-18 22:38
No joy I'm afraid:

```
[11:37:29 PM] Starting Sid Meier's Civilization VI
   Unexpected download error : An unexpected error occured while downloading manifests!  Skipping...
```

**Comment by tpill90** [comment] 2022-08-19 00:47
I'm attaching another build that will log some more detailed error messages to a file.  
Could you attempt to prefill Civilization again with this version, and upload the the **errorlog.txt** from the application's directory?
[SteamPrefill-1.3.0-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9378417/SteamPrefill-1.3.0-linux-x64.zip)
[SteamPrefill-1.3.0-osx-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9378418/SteamPrefill-1.3.0-osx-x64.zip)
[SteamPrefill-1.3.0-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9378419/SteamPrefill-1.3.0-win-x64.zip)
[SteamPrefill-1.3.0-linux-arm64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9378420/SteamPrefill-1.3.0-linux-arm64.zip)

**Comment by dilsonn** [comment] 2022-08-19 09:31
This is an attempt using the build above for 'Burnout™ Paradise Remastered':

```
[[9:29:44 AM]] An exception occurred while downloading manifests[[9:29:44 AM]] SteamPrefill.Models.Exceptions.ManifestException: No manifest request code was returned for 1238081 8811929432089288301
   at SteamPrefill.Handlers.ManifestHandler.GetManifestRequestCodeAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot, Server server)
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_1.<<AttemptManifestDownloadAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_0.<<AttemptManifestDownloadAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Internal\DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 116
   at Spectre.Console.Status.StartAsync[T](String status, Func`2 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 77
   at SteamPrefill.Handlers.ManifestHandler.AttemptManifestDownloadAsync(List`1 depots)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)[[9:29:45 AM]] An exception occurred while downloading manifests[[9:29:45 AM]] SteamPrefill.Models.Exceptions.ManifestException: No manifest request code was returned for 1238082 4526578194170578880
   at SteamPrefill.Handlers.ManifestHandler.GetManifestRequestCodeAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot, Server server)
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_1.<<AttemptManifestDownloadAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_0.<<AttemptManifestDownloadAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Internal\DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 116
   at Spectre.Console.Status.StartAsync[T](String status, Func`2 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 77
   at SteamPrefill.Handlers.ManifestHandler.AttemptManifestDownloadAsync(List`1 depots)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)[[9:29:46 AM]] An exception occurred while downloading manifests[[9:29:46 AM]] SteamPrefill.Models.Exceptions.ManifestException: No manifest request code was returned for 1238081 8811929432089288301
   at SteamPrefill.Handlers.ManifestHandler.GetManifestRequestCodeAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot, Server server)
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_1.<<AttemptManifestDownloadAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_0.<<AttemptManifestDownloadAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Internal\DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 116
   at Spectre.Console.Status.StartAsync[T](String status, Func`2 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 77
   at SteamPrefill.Handlers.ManifestHandler.AttemptManifestDownloadAsync(List`1 depots)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)
```

**Comment by tpill90** [comment] 2022-08-19 14:38
I've got another build that adds slightly more info to the error log.  Would you mind giving it another try?

[SteamPrefill-1.3.0-linux-arm64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9382991/SteamPrefill-1.3.0-linux-arm64.zip)
[SteamPrefill-1.3.0-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9382992/SteamPrefill-1.3.0-linux-x64.zip)
[SteamPrefill-1.3.0-osx-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9382989/SteamPrefill-1.3.0-osx-x64.zip)
[SteamPrefill-1.3.0-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9382990/SteamPrefill-1.3.0-win-x64.zip)

**Comment by dilsonn** [comment] 2022-08-19 15:37
```
[[3:37:02 PM]] An exception occurred while downloading manifests[[3:37:02 PM]] SteamPrefill.Models.Exceptions.ManifestException: No manifest request code was returned for 1238080 1238081 8811929432089288301
   at SteamPrefill.Handlers.ManifestHandler.GetManifestRequestCodeAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot, Server server)
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_1.<<AttemptManifestDownloadAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_0.<<AttemptManifestDownloadAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Internal\DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 116
   at Spectre.Console.Status.StartAsync[T](String status, Func`2 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 77
   at SteamPrefill.Handlers.ManifestHandler.AttemptManifestDownloadAsync(List`1 depots)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)[[3:37:03 PM]] An exception occurred while downloading manifests[[3:37:03 PM]] SteamPrefill.Models.Exceptions.ManifestException: No manifest request code was returned for 1238080 1238081 8811929432089288301
   at SteamPrefill.Handlers.ManifestHandler.GetManifestRequestCodeAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot, Server server)
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_1.<<AttemptManifestDownloadAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_0.<<AttemptManifestDownloadAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Internal\DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 116
   at Spectre.Console.Status.StartAsync[T](String status, Func`2 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 77
   at SteamPrefill.Handlers.ManifestHandler.AttemptManifestDownloadAsync(List`1 depots)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)[[3:37:04 PM]] An exception occurred while downloading manifests[[3:37:04 PM]] SteamPrefill.Models.Exceptions.ManifestException: No manifest request code was returned for 1238080 1238081 8811929432089288301
   at SteamPrefill.Handlers.ManifestHandler.GetManifestRequestCodeAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot, Server server)
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_1.<<AttemptManifestDownloadAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_0.<<AttemptManifestDownloadAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Internal\DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 116
   at Spectre.Console.Status.StartAsync[T](String status, Func`2 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 77
   at SteamPrefill.Handlers.ManifestHandler.AttemptManifestDownloadAsync(List`1 depots)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)
```

**Comment by stuart-c-moore** [comment] 2022-08-19 21:51
Civ6 still failing, here is the error log:

```
stuart@lancache:~/SteamPrefill-1.3.0-linux-x64$ cat errorlog.txt
[[10:48:40 PM]] An exception occurred while downloading manifests[[10:48:40 PM]] SteamPrefill.Models.Exceptions.ManifestException: No manifest request code was returned for 1523210 1523211 4005512837758401031
   at SteamPrefill.Handlers.ManifestHandler.GetManifestRequestCodeAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot, Server server)
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_1.<<AttemptManifestDownloadAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_0.<<AttemptManifestDownloadAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Internal\DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 116
   at Spectre.Console.Status.StartAsync[T](String status, Func`2 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 77
   at SteamPrefill.Handlers.ManifestHandler.AttemptManifestDownloadAsync(List`1 depots)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)[[10:48:44 PM]] An exception occurred while downloading manifests[[10:48:44 PM]] SteamPrefill.Models.Exceptions.ManifestException: No manifest request code was returned for 1523210 1523211 4005512837758401031
   at SteamPrefill.Handlers.ManifestHandler.GetManifestRequestCodeAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot, Server server)
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_1.<<AttemptManifestDownloadAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_0.<<AttemptManifestDownloadAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Internal\DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 116
   at Spectre.Console.Status.StartAsync[T](String status, Func`2 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 77
   at SteamPrefill.Handlers.ManifestHandler.AttemptManifestDownloadAsync(List`1 depots)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)[[10:48:52 PM]] An exception occurred while downloading manifests[[10:48:52 PM]] SteamPrefill.Models.Exceptions.ManifestException: No manifest request code was returned for 1523210 1523211 4005512837758401031
   at SteamPrefill.Handlers.ManifestHandler.GetManifestRequestCodeAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot, Server server)
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_1.<<AttemptManifestDownloadAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_0.<<AttemptManifestDownloadAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Internal\DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 116
   at Spectre.Console.Status.StartAsync[T](String status, Func`2 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 77
   at SteamPrefill.Handlers.ManifestHandler.AttemptManifestDownloadAsync(List`1 depots)
```

**Comment by tpill90** [comment] 2022-08-22 18:27
[SteamPrefill-1.3.1-osx-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9396702/SteamPrefill-1.3.1-osx-x64.zip)
[SteamPrefill-1.3.1-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9396704/SteamPrefill-1.3.1-win-x64.zip)
[SteamPrefill-1.3.1-linux-arm64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9396705/SteamPrefill-1.3.1-linux-arm64.zip)
[SteamPrefill-1.3.1-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9396706/SteamPrefill-1.3.1-linux-x64.zip)

@dilsonn Could you give this build another shot?

**Comment by tpill90** [comment] 2022-08-31 16:26
Closing as this issue seems to be fixed in the latest release.  Feel free to reopen if the issue still persists

**Closed by tpill90** 2022-08-31 16:26 UTC
Labels: bug
