### ISSUE TITLE
Pre-filled cache not being picked up by Steam - lancache works as if there was no SteamPrefill

### ISSUE THREAD

**Issue by nazgul6** [tpill90/steam-lancache-prefill#333] opened 2023-10-22 10:52 UTC
A rather interesting issue....

SteamPrefill _appears_ to work just fine for me - have c.75 games pre-filled, c.750GB in total, to my SSD. App.log is clean. No errors.

However, trying to install a game that I know is successfully prefilled with SteamPrefilled using the Steam client, it appears the pre-fill is ignored - in other words, the initial download is from Steam's servers (exactly capped at my top internet speed 33.5MB/s), if I then uninstall the game and re-install it, my lancache gets engaged and serves the files at 1gbit local LAN speed.

I tried this with two different games and on different Steam gaming setups (one on Windows 10 and one on Linux).

Any ideas what the reason could be / how to troubleshoot?

**Comment by IIPoliII** [comment] 2023-10-25 16:24
I have the same issue

**Comment by tpill90** [comment] 2023-10-27 20:59
@nazgul6 @IIPoliII 

A few things...
- Do you remember which app(s) were the ones affected?  Is it one specifically, or multiple, or all of them?
- What is your `CACHE_DISK_SIZE` environment variable set to in your `.env` file (or elsewhere depending on your setup)
- When the issue is occurring, does the `access.log` show the requests as a `MISS`?

**Comment by IIPoliII** [comment] 2023-10-28 14:11
> @nazgul6 @IIPoliII
> 
> A few things...
> 
> * Do you remember which app(s) were the ones affected?  Is it one specifically, or multiple, or all of them?
> * What is your `CACHE_DISK_SIZE` environment variable set to in your `.env` file (or elsewhere depending on your setup)
> * When the issue is occurring, does the `access.log` show the requests as a `MISS`?

Hello!
It was with `TEKKEN 7 - 389730`
The `CACHE_DISK_SIZE` was set at `2000G` at the time, it was the first download, the other cache parameter was set to 2000M
In the access.log from what I saw it was accessing different cache server from steam client, if I am not wrong. 
So it was Miss, but then instead of taking for exemple 70gb the game actually took 140 (so like if it was downloaded twice?)

Sadly I had to manually already download it on my PC as the LAN is really soon. If once I got the time to spin it up again I will do the test again.

**Comment by tpill90** [comment] 2023-10-28 19:14
Could you do one more thing for me regarding Tekken. Could you download it through both Steam and SteamPrefill and compare the download size between both applications? I wonder if there's parts of the game that SteamPrefill is missing

**Comment by nazgul6** [comment] 2023-10-28 19:52
Thanks @tpill90 for looking into this.

CACHE_DISK_SIZE=2000g

Whilst I don't remember the original games I tried, here's a couple of random tests I just ran on my endeavourOS Linux machine:
- Mirror's Edge - seemed to install from lancache, albeit there’s a few MISSes in the log
- BioShock - as above, HITs were on depot 7701, MISSes on depot 7670
- Borderlands 2 - mostly (if not all) MISSes in logs - so presumably installed fully from Steam’s servers as the speed was capped at my ISP speed the full installed. Uninstalled, then re-installed and lancache served the install files this time - not a single MISS this time

**Comment by tpill90** [comment] 2023-12-27 00:15
Since there hasn't been any new info on this for awhile, I'm going to close this.

If this issue does pop up again for any of you please feel free to re-open this issue and we'll dig in deeper again.

**Closed by tpill90** 2023-12-27 00:15 UTC
