### ISSUE TITLE
Timeout connecting to Steam network

### ISSUE THREAD

**Issue by Minc3** [tpill90/steam-lancache-prefill#376] opened 2024-08-28 00:41 UTC
It's been working fine for months but all of a sudden it stop being able to connect to steam.
Every 4 hours I had a script run ./SteamPrefill prefill just to keep everything up to date.

I'm not sure if I'm updating to frequently and steam has limited me or if something else it going on here.

```
[10:28:04 AM] Already disconnected from Steam
SteamPrefill.Models.Exceptions.SteamConnectionException: Timeout connecting to Steam...  Try again in a few moments
  at void SteamPrefill.Handlers.Steam.Steam3Session.ConnectToSteam()
  at void SteamPrefill.Handlers.Steam.Steam3Session.<>c__DisplayClass16_0.<<LoginToSteamAsync>b__0>d.MoveNext()
  at void Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in Status.cs:79
  at void Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in Status.cs:120
  at void Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in Progress.cs:133
  at async Task<T> Spectre.Console.Internal.DefaultExclusivityMode.RunAsync<T>(Func<Task<T>> func) in
     DefaultExclusivityMode.cs:40
  at async Task<T> Spectre.Console.Progress.StartAsync<T>(Func<ProgressContext, Task<T>> action) in Progress.cs:116
  at async Task<T> Spectre.Console.Status.StartAsync<T>(string status, Func<StatusContext, Task<T>> func) in Status.cs:
     117
  at async Task Spectre.Console.Status.StartAsync(string status, Func<StatusContext, Task> action) in Status.cs:77
  at async Task SteamPrefill.Handlers.Steam.Steam3Session.LoginToSteamAsync()
  at async Task SteamPrefill.SteamManager.InitializeAsync()
  at async ValueTask SteamPrefill.CliCommands.SelectAppsCommand.ExecuteAsync(IConsole console)
  at async ValueTask<int> CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput)
     in CliApplication.cs:148
  at async ValueTask<int> CliFx.CliApplication.RunAsync(IReadOnlyList<string> commandLineArguments,
     IReadOnlyDictionary<string, string> environmentVariables) in CliApplication.cs:190
  at async ValueTask<int> CliFx.CliApplication.RunAsync(IReadOnlyList<string> commandLineArguments) in CliApplication.cs
     :202
  at async Task<int> SteamPrefill.Program.Main()
```
  
[app.log](https://github.com/user-attachments/files/16772378/app.log)

**Comment by Morpheus84h** [comment] 2024-08-28 06:51
I have the same Error with all Prefill-Profiles, but Steam working very great, (also downloads from lancache)

**Comment by Hamsterman** [comment] 2024-08-28 14:43
Getting timeouts on Steam aswell

**Comment by Hamsterman** [comment] 2024-08-28 14:49
And now it works again for me.

**Comment by TheRedHerring95** [comment] 2024-08-29 01:52
Also getting the same issue, only on the Prefill tool; not sure if they changed something yesterday while they were down, though if it's working for @Hamsterman that wouldn't necessarily make sense. Was originally running on 2.5.0 but updated to 2.6.1 and got the same issue, then cleared the account config in case that had gotten messed up along the line, but the issue is persisting

**Comment by tpill90** [comment] 2024-08-29 02:38
I believe that there is something going on with Steam's servers at the moment, or they changed something like you mentioned @TheRedHerring95 with yesterday's update.  I'm currently seeing the issue myself, and it appears to be regionally affected with not all regions having this issue.  I'm on the East Coast US and I'm having difficulty when attempting to login to Steam's Virginia servers.  I've had luck with being able to login through Austria or Japan.

As a workaround for this try running SteamPrefill's `clear-cache` command and then trying to run the prefill again.  You might have to do this a few times to get it to cycle over to an appropriate server, which could be made a bit easier by adding the `-y` flag to `clear-cache`.

**Comment by Minc3** [comment] 2024-08-29 05:05
Can confirm running ./SteamPrefill clear-cache -y then doing a prefill allows it to work 50% of the time.
The only problem is you need to keep clearing cache or it will just keep failing to connect.

`/bin/docker exec lancache-monolithic bash -c "/scripts/prefill/./SteamPrefill clear-cache -y && /scripts/prefill/./SteamPrefill prefill"`

**Comment by Morpheus84h** [comment] 2024-08-29 18:03
I don't have the prefiller in a docker and i tried that clear cache but it doesn't work on any way

**Comment by PastedBoi** [comment] 2024-08-29 19:41
> I believe that there is something going on with Steam's servers at the moment, or they changed something like you mentioned @TheRedHerring95 with yesterday's update. I'm currently seeing the issue myself, and it appears to be regionally affected with not all regions having this issue. I'm on the East Coast US and I'm having difficulty when attempting to login to Steam's Virginia servers. I've had luck with being able to login through Austria or Japan.
> 
> As a workaround for this try running SteamPrefill's `clear-cache` command and then trying to run the prefill again. You might have to do this a few times to get it to cycle over to an appropriate server, which could be made a bit easier by adding the `-y` flag to `clear-cache`.

Having the probably same issue (in Germany), but its very consistent for me that a seperate clear-cache allows for one single prefill after which i have to clear-cache again. Have not yet tried combining the commands yet.

**Comment by reg98643t** [comment] 2024-08-30 00:39
Glad I'm not the only one getting the issue, I'm using dockerised prefill and clear-cache seems to do nothing for me.

**Comment by tpill90** [comment] 2024-08-30 01:21
I've pushed up a build hardcoded to use the Vienna region which seems to work reliably for me.  Performance will likely be degraded depending on where you're located, but it should work as a holdover until I can get the time to diagnose this issue properly.

Build can be downloaded here : https://github.com/tpill90/steam-lancache-prefill/actions/runs/10625042739

**Comment by reg98643t** [comment] 2024-08-30 10:40
That build seems to work for me, speed seems alright. Thanks!

**Comment by megaeverything** [comment] 2024-08-31 06:58
Same issue connecting to east coast steam servers

**Comment by andrepue** [comment] 2024-09-01 16:45
Hi. I also have the problems ere. out of 10 connection trials only one succeds... sometimes. I found soemthing interesting in the Docke Log Files. The Time is off by 4 hours. Could this be related to the connection issues? How can I setup the correct Timezone? I am using a Docker Container on Unraid.

Regards, André

**Comment by PastedBoi** [comment] 2024-09-01 17:36
> Hi. I also have the problems ere. out of 10 connection trials only one succeds... sometimes. I found soemthing interesting in the Docke Log Files. The Time is off by 4 hours. Could this be related to the connection issues? How can I setup the correct Timezone? I am using a Docker Container on Unraid.
> 
> Regards, André

This happens regardless of timezone/time difference.
This is offtopic but make sure you have set the timezone in unraid correctly, docker normally uses the timezone of the host system. If that doesnt work change the timezone of the container via the extra parameters of the container.

**Comment by tpill90** [comment] 2024-09-01 18:24
I've pushed up a test build which seems to fix this issue here : https://github.com/tpill90/steam-lancache-prefill/actions/runs/10656333448

Could I get a few people to test this out, preferably in a few different regions.  I'm on the East Coast US and I've tested it as working here.  If you do test it I am interested in the following info, you should add the option `--debug` to your prefill run in order to get some of this information to print out :

- What region you are located in
- How frequently does SteamPrefill connect successfully?
- How long the Steam connection takes, as well as how long it takes to load all of the appropriate app metadata.  Attaching a photo like this is fine: 

![image](https://github.com/user-attachments/assets/16efc07c-4346-4d6f-bd7a-2ac7b7b46fdc)

**Comment by PastedBoi** [comment] 2024-09-01 18:43
With the test build im getting:
Region Germany: ext4-fra1 sometimes fra2
Successful Connections: With the test build i havent had a failed connection yet in the ~15 or so tries i did
![steam-lancache-console](https://github.com/user-attachments/assets/679acfb4-bf30-4087-b3c0-9126757752a0)

**Comment by Morpheus84h** [comment] 2024-09-01 18:52
With the testbuild im getting

Region Germany ( NRW, 65km north from Oberhausen) the
Unspecified/ext2-ams1.steamserver.net  -Server every time

and it works :-)

**Comment by tpill90** [comment] 2024-09-01 19:39
This is testing is enough for me. I'll push up an update tonight

**Comment by tpill90** [comment] 2024-09-02 23:35
I've pushed this up in [v2.7.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v2.7.0).  If anyone still has issues please let me know on this ticket.

**Comment by zaunermax** [comment] 2024-10-10 11:39
I am indeed getting timeouts again, I am on version 2.8.0 - yesterday it seemed to work still 🤔

**Comment by tpill90** [comment] 2024-10-10 16:07
Thank you for the report!  Re-opening

**Comment by tpill90** [comment] 2024-10-10 16:20
It appears that the Steam network is no longer allowing WebSocket connections in multiple regions.  So far some of the affected regions that I'm aware of are : 

| Cell Id | Short | City              |
|---------|-------|-------------------|
| 1       | ord   | Chicago           |
| 4       | lhr   | London            |
| 5       | fra   | Frankfurt         |
| 15      | ams   | Amsterdam         |
| 31      | sea   | Seattle           |
| 33      | hkg   | Hong Kong         |
| 50      | atl   | Atlanta           |
| 63      | iad   | Washington, DC    |
| 64      | lax   | Los Angeles       |
| 65      | dfw   | Dallas Fort-Worth |
| 92      | vie   | Vienna            |

Some of the working regions:

| Cell Id | Short | City              |
|---------|-------|-------------------|
| 14      | par   | Paris             |
| 25      | gru   | Sao Paulo         |
| 32      | tyo   | Japan             |
| 35      | sgp   | Singapore         |
| 38      | waw   | Poland            |
| 40      | mad   | Madrid            |
| 52      | syd   | Sydney            |
| 66      | sto   | Stockholm         |

**Comment by mdCllang** [comment] 2024-10-11 07:58
Can we as a workaround set our cell id to a region that is currently supported ? or will that have some negative effects like wrong language packs from games?

My Cell id is usally 5

**Comment by W0rkingChr1s** [comment] 2024-10-11 08:45
Good Morning, I am heading to the same Problem here. I am using the Linux Installation to an dockerized LanCache. The last days it worked fine but now I am getting this error: (error log first without cellid, then with cellid 5, the last with cellid 14)
`[8:42:56 AM] Starting login!
[8:42:57 AM] Connecting with CellId: 0
[8:43:27 AM] Already disconnected from Steam
[8:43:27 AM] SteamPrefill.Models.Exceptions.SteamConnectionException: Timeout connecting to Steam...  Try again in a few moments
   at SteamPrefill.Handlers.Steam.Steam3Session.ConnectToSteam()
   at SteamPrefill.Handlers.Steam.Steam3Session.<>c__DisplayClass16_0.<<LoginToSteamAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in Spectre.Console\Live\Status\Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in Spectre.Console\Live\Status\Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in Spectre.Console\Live\Progress\Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync(Func`1 func) in Spectre.Console\Internal\DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync(Func`2 action) in Spectre.Console\Live\Progress\Progress.cs:line 116
   at Spectre.Console.Status.StartAsync(String status, Func`2 func) in Spectre.Console\Live\Status\Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in Spectre.Console\Live\Status\Status.cs:line 77
   at SteamPrefill.Handlers.Steam.Steam3Session.LoginToSteamAsync()
   at SteamPrefill.SteamManager.InitializeAsync()
   at SteamPrefill.CliCommands.SelectAppsCommand.ExecuteAsync(IConsole console)
   at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in CliFx\CliApplication.cs:line 148
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in CliFx\CliApplication.cs:line 190
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments) in CliFx\CliApplication.cs:line 202
   at SteamPrefill.Program.Main()
[8:43:37 AM] Using --cellid flag.  Will force the usage of cell id 5
[8:43:38 AM] Starting login!
[8:43:38 AM] Connecting with CellId: 5
[8:44:08 AM] Already disconnected from Steam
[8:44:08 AM] SteamPrefill.Models.Exceptions.SteamConnectionException: Timeout connecting to Steam...  Try again in a few moments
   at SteamPrefill.Handlers.Steam.Steam3Session.ConnectToSteam()
   at SteamPrefill.Handlers.Steam.Steam3Session.<>c__DisplayClass16_0.<<LoginToSteamAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in Spectre.Console\Live\Status\Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in Spectre.Console\Live\Status\Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in Spectre.Console\Live\Progress\Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync(Func`1 func) in Spectre.Console\Internal\DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync(Func`2 action) in Spectre.Console\Live\Progress\Progress.cs:line 116
   at Spectre.Console.Status.StartAsync(String status, Func`2 func) in Spectre.Console\Live\Status\Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in Spectre.Console\Live\Status\Status.cs:line 77
   at SteamPrefill.Handlers.Steam.Steam3Session.LoginToSteamAsync()
   at SteamPrefill.SteamManager.InitializeAsync()
   at SteamPrefill.CliCommands.SelectAppsCommand.ExecuteAsync(IConsole console)
   at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in CliFx\CliApplication.cs:line 148
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in CliFx\CliApplication.cs:line 190
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments) in CliFx\CliApplication.cs:line 202
   at SteamPrefill.Program.Main()
[8:44:16 AM] Using --cellid flag.  Will force the usage of cell id 14
[8:44:17 AM] Starting login!
[8:44:17 AM] Connecting with CellId: 14
[8:44:19 AM] Connected to Steam!`

**Comment by zaunermax** [comment] 2024-10-11 10:16
Thanks for the quick response, the `cellid` command worked like a charm!

**Comment by tpill90** [comment] 2024-10-11 12:55
> Can we as a workaround set our cell id to a region that is currently supported ? or will that have some negative effects like wrong language packs from games?
> 

Steam currently only uses the `CellId` to determine which cluster of connection managers to try to connect to.  The connection managers are located in different regions so that they're closer to the end user for better performance.  You can take a look at [https://steamstat.us](https://steamstat.us/) to see the regions and their current status.

CellId isn't used at all in determining what language specific assets will be downloaded, that is usually specified by the user in the real Steam client.  SteamPrefill however is hardcoded to use English.

> I saw in your code you wait 50 milisecs what is may a bit to less for some slower networks. May wait at least 1 sek

Is this the line that you're referring to? `_callbackManager.RunWaitAllCallbacks(timeout: TimeSpan.FromMilliseconds(50));`

**Comment by W0rkingChr1s** [comment] 2024-10-11 13:49
Try to use the cellid command './Steamprefill prefill --cellid 14'

**Comment by Haf08** [comment] 2024-10-15 16:30
Hey, I am facing the same issue, its running in docker on Unraid, and even trying different cellid does not work.


![prefill_error](https://github.com/user-attachments/assets/7a1080fe-cbf1-45b9-95c3-84a84216b9ae)

**Comment by makejoint** [comment] 2024-10-15 21:42
as @W0rkingChr1s mentioned, if WebSocket fails, then launching one time `./Steamprefill prefill --cellid 14`, then interrupting with Ctrl-C and restarting without cellid, then works for me. Location Germany (Frankfurt server I suppose).

**Comment by makejoint** [comment] 2024-10-15 21:44
and pls before posting, launch with `--debug`, such that one can see what's going on in the background

**Comment by mdCllang** [comment] 2024-10-16 12:18
> @mdCllang Try to use the cellid command `./Steamprefill prefill --cellid 14`

@tpill90 
i tested now some days here is my update:

i use also unraid by default my cell id was detected as FRA (5) as a context information for @Haf08  post
i wiped out my cache to test from scratch 

i used as recommended cellid 14.
it stable founds at least one server to connect with (pool of 200 servers)
and starts downloading.

I spotted disconnections during a running downloads (socket closed)
eg. 
10%
20%
socket closed exception

Stream prefill than just stopped until next cron exectution (Maybe a improvment could be do a connect retry at least one or two times.)

next issue related on this behavior:
because of stopped by exeption. it started again fully from beginning even already fully downloaded depos are requested.
of course this time the chache responded.

eg sample flow:

99%
100% (GameA fully downloaded)

(start new game GameB)
0%
10%
socket closed exception

(Next cron iteration)
GameA (super fast this time already in cache)
0%
99%
100%
(start new game GameB)
0%
10% -> fast until here
20%
30%
......
socket closed exception
and so on

butit seams to be steamprefill must run a full fun without any execptions to update the "already downloaded list" at least it looks like for me.
so it took quite a time until my cache was full enought to grap the last few bytes not in cache without getting a socket closed exception.

the reason it took serveral days is that i run my cron only once per day/night.

if you need more details or something is not good understandable give me a note

**Comment by Haf08** [comment] 2024-10-16 17:54
> as @W0rkingChr1s mentioned, if WebSocket fails, then launching one time `./Steamprefill prefill --cellid 14`, then interrupting with Ctrl-C and restarting without cellid, then works for me. Location Germany (Frankfurt server I suppose).

I unfortunately cannot run prefill because than it say no such file or directory, so I had to run it with select-apps so here you go 
[message.txt](https://github.com/user-attachments/files/17400717/message.txt)

**Comment by tpill90** [comment] 2024-10-17 16:35
I pushed up a test build for everyone to try.  You can download it at the bottom of this page when you are logged into Github : https://github.com/tpill90/steam-lancache-prefill/actions/runs/11389097563

When testing this build, please run the following commands:
```
.\SteamPrefill clear-temp -y
.\SteamPrefill prefill
```

Since there are a lot of people following this thread and it is likely to generate a lot of replies that could cause messages to get lost in the volume,  I would please ask you to report whether or not the build worked for you using emojis.  Please use ✅ if SteamPrefill was able to connect and function as normal,  otherwise use ❌ .

**Comment by tpill90** [comment] 2024-10-22 15:33
I've pushed up a new version that should include the fix [v2.9.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v2.9.0)

I'm going to leave this issue open for now so that it can keep tracking whether the new build is working as intended or not.

**Comment by reg98643t** [comment] 2024-10-24 01:21
Absolutely love your work mate, thank you.

Kind regards,
Lachlan Haase
***@***.*** 078 024 (Unavailable by phone business hours, please email or SMS)

**Comment by makejoint** [comment] 2024-10-25 07:16
works like a charm for me. Thank you @tpill90

**Comment by tpill90** [comment] 2024-11-23 22:23
Closing this out since it seems like the fix has been working as intended.  Thanks everyone for the help figuring this out!

**Closed by tpill90** 2024-11-23 22:23 UTC
Labels: bug

**Comment by makejoint** [comment] 2024-11-23 22:24
Thank you for your passionate work!
