### ISSUE TITLE
[Feature Request] Provide Docker Container Image

### ISSUE THREAD

**Issue by spyfly** [tpill90/steam-lancache-prefill#58] opened 2022-08-05 22:50 UTC
Enables automatic updates, using software such as watchtower.

**Comment by SamTV12345** [comment] 2022-08-24 21:04
Great idea. I'm going to check this out.

**Comment by SamTV12345** [comment] 2022-08-25 14:06
Somebody was faster than me. Please have a look at https://gitlab.com/kirbo/steam-prefill-docker .

**Comment by tpill90** [comment] 2022-08-25 15:29
Closing this issue, as its a duplicate of https://github.com/tpill90/steam-lancache-prefill/issues/94 which was created to integrate Kirbo's repo into this one, to officially support Docker

**Closed by tpill90** 2022-08-25 15:29 UTC
Labels: duplicate, feature request
