### ISSUE TITLE
Websocket exceptions when using SteamGuard Mobile App

### ISSUE THREAD

**Issue by xvzf** [tpill90/steam-lancache-prefill#387] opened 2024-10-10 09:31 UTC
**Describe the bug**
When authenticating with a steam account with the SteamGuard Mobile App enabled (Press to confirm login), the process can either stall or after successfully authenticating fail when connecting to the remote server (see last section)

A tcpdump shows the connection is terminated by the remote server.
 
**Additional Details**
 - Platform you are running SteamPrefill on: Linux/ALpine
 - Discord Username: m4tbit

**Logs**
Flooded with

```
[9:27:06 AM] ServerList: Next server candidate: Unspecified/ext4-fra2.steamserver.net:27036 (WebSocket)
[9:27:06 AM] f9b5f3e02126499ca122bf833b4aabc3/WebSocketContext: Exception connecting websocket: System.Net.WebSockets.WebSocketException - Unable to connect to the remote server
[9:27:06 AM] ServerList: Next server candidate: Unspecified/ext3-fra1.steamserver.net:27035 (WebSocket)
[9:27:06 AM] f9b5f3e02126499ca122bf833b4aabc3/WebSocketContext: Exception connecting websocket: System.Net.WebSockets.WebSocketException - Unable to connect to the remote server
[9:27:06 AM] ServerList: Next server candidate: Unspecified/ext3-fra2.steamserver.net:27037 (WebSocket)
[9:27:06 AM] f9b5f3e02126499ca122bf833b4aabc3/WebSocketContext: Exception connecting websocket: System.Net.WebSockets.WebSocketException - Unable to connect to the remote server
[9:27:06 AM] Already disconnected from Steam
[9:27:06 AM] SteamPrefill.Models.Exceptions.SteamConnectionException: Timeout connecting to Steam...  Try again in a few moments
   at SteamPrefill.Handlers.Steam.Steam3Session.ConnectToSteam()
   at SteamPrefill.Handlers.Steam.Steam3Session.<>c__DisplayClass16_0.<<LoginToSteamAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in Spectre.Console\Live\Status\Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in Spectre.Console\Live\Status\Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in Spectre.Console\Live\Progress\Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync(Func`1 func) in Spectre.Console\Internal\DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync(Func`2 action) in Spectre.Console\Live\Progress\Progress.cs:line 116
   at Spectre.Console.Status.StartAsync(String status, Func`2 func) in Spectre.Console\Live\Status\Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in Spectre.Console\Live\Status\Status.cs:line 77
   at SteamPrefill.Handlers.Steam.Steam3Session.LoginToSteamAsync()
   at SteamPrefill.SteamManager.InitializeAsync()
   at SteamPrefill.CliCommands.PrefillCommand.ExecuteAsync(IConsole console)
   at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in CliFx\CliApplication.cs:line 148
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in CliFx\CliApplication.cs:line 190
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments) in CliFx\CliApplication.cs:line 202
   at SteamPrefill.Program.Main()
```

**Comment by tpill90** [comment] 2024-10-10 16:09
I'm marking this as a duplicate since I believe that this is the same issue as #376.  I will leave this open for tracking purposes until the root issue is fixed.

**Comment by tpill90** [comment] 2024-11-23 22:24
Closing this out since it seems like the fix has been working as intended.

**Closed by tpill90** 2024-11-23 22:24 UTC
Labels: bug, duplicate
