### ISSUE TITLE
select-apps: selected games not visible, layout does not match documentation

### ISSUE THREAD

**Issue by FreelancerJay** [tpill90/steam-lancache-prefill#176] opened 2022-10-14 03:25 UTC
Hi, first of all love your pre-filler. In terms of function, totally nailing it. Thank you for making it, and sharing it!

Just updated to 1.6.0, and unfortunately the new Select-Apps interface is botched for me.
- As you scroll through entries, the highlighted one is not visible
- Selected entries are not visible
- Most of the UI seems to be greyed out. I'm basing that on comparing what I see on my console to what is in the documentation

The environment is a Debian 11 LXC, running alongside my LanCache itself, and is accessed via lxc-attach. The terminal is xtermjs

Let me know what else would be useful to know to debug!

![Screen Shot 2022-10-14 at 2 20 48 pm](https://user-images.githubusercontent.com/67540736/195755344-74a7ecd0-8fdb-4622-917e-8b97ea9b0741.png)

**Comment by tpill90** [comment] 2022-10-15 19:12
Hi @FreelancerJay,

I would like to know what the output of `echo $TERM` gives you from your terminal.  I believe the issue here is being caused due to the Tui library I am using requiring the terminal to have support for 256 color pallette : `export TERM=xterm-256color`.

**Comment by FreelancerJay** [comment] 2022-10-16 06:26
> I would like to know what the output of `echo $TERM` gives you from your terminal. I believe the issue here is being caused due to the Tui library I am using requiring the terminal to have support for 256 color pallette : `export TERM=xterm-256color`.

Well the output for me is `linux`, which is... unhelpful. But did get me thinking. I ran `tput colors` and it reports I've got 8 supported. 

So I'll work on getting it set for 256 support.

Perhaps it would be worth running a check when running to see how many colours are supported. The old UI worked fine for me visually, so maybe a switch checking that the terminal is supporting enough colours which falls back to the old UI if it's below 256? Or if you're wanting to dump the old UI, then just a message saying "you need moar colorz" to redirect others in the future :-)

Thanks for taking a look!

**Comment by tpill90** [comment] 2022-10-16 16:17
I think that a combination of the two sounds like the correct solution. I don't necessarily want to support both of them, but at the same time I don't want to require users to have to do some manual configuration to use my app. So maybe in the case that their terminal doesn't have full color support, there is a message warning them how to fix it, and then falls back to the original UI

**Comment by irishj** [comment] 2022-10-25 21:33
Seeing the same issue within the terminal of a lancache docker container, run from Portainer.

Output of "echo $TERM" is "xterm"
Output of "tput colors" is "8"

Solved the issue by using the 'custom command' option and entering "env TERM=xterm-256color /bin/bash".  Just in case anyone else runs into the same issue.  Thanks for a great tool !

**Comment by tpill90** [comment] 2022-10-28 20:58
This issue seems to be related to this https://github.com/gui-cs/Terminal.Gui/issues/2085

**Comment by tpill90** [comment] 2022-10-28 21:28
I believe I've found a fix, and I've tested it against the following :

## Putty
![image](https://user-images.githubusercontent.com/766513/198735722-20ef9a2f-c7a9-4194-9673-9b64bd36ab5b.png)

## Debian 11
![image](https://user-images.githubusercontent.com/766513/198735801-8dca9358-5c7e-4a4e-bb00-c30ffa62a628.png)

## Windows Terminal
![image](https://user-images.githubusercontent.com/766513/198735886-2f5b37bc-e65c-4827-8b0f-20932b7c6d73.png)

**Comment by tpill90** [comment] 2022-10-28 21:44
@FreelancerJay Could you give this test build a shot? 
https://github.com/tpill90/steam-lancache-prefill/actions/runs/3348717144

**Comment by FreelancerJay** [comment] 2022-10-28 22:28
Fist thing when I’m hope from work, will test and report back

**Comment by FreelancerJay** [comment] 2022-10-30 00:44
@tpill90, worked like a charm, didn't need to modify $TERM to run that and could still see everything fine!

**Comment by tpill90** [comment] 2022-10-30 01:46
Fantastic!  I'll get this merged and included in the next release

**Comment by LilTrublMakr** [comment] 2022-11-06 01:34
Unfortunately, still having a problem with this on 1.7.3. I have tried MobaXTerm, PuTTY, and Unraids terminal.

https://cdn.discordapp.com/attachments/999228019883380746/1038626584644571176/Screenshot_2022-11-05_213057.png

**Comment by tpill90** [comment] 2023-01-18 21:12
Closing this as I haven't received enough information to reproduce the issue.

**Closed by tpill90** 2023-01-18 21:12 UTC
Labels: bug
