### ISSUE TITLE
Failed to create CoreCLR, HRESULT: 0x80004005

### ISSUE THREAD

**Issue by JulyIghor** [tpill90/steam-lancache-prefill#236] opened 2022-12-15 08:52 UTC
It fails to run on Raspberry OS arm64
I downloaded latest arm64 release and docker image built successfully, but it won't start.

**Comment by JulyIghor** [comment] 2022-12-16 05:16
Replacing the path /SteamPrefill by /usr/bin/SteamPrefill fixes the issue

**Comment by tpill90** [comment] 2022-12-19 23:17
Closing this issue as it seems to be resolved.  Please feel free to reopen if needed.

**Comment by JulyIghor** [comment] 2022-12-19 23:32
> Closing this issue as it seems to be resolved.  Please feel free to reopen if needed.

It is good if you patch it so it will be fixed for everyone this way

**Comment by tpill90** [comment] 2022-12-19 23:35
Could you please walk me through what you did to reproduce this?
Was it:
- Download the latest arm64 release
- Build a docker image using the Dockerfile included in this repo?

**Comment by JulyIghor** [comment] 2022-12-20 00:11
> Could you please walk me through what you did to reproduce this? Was it:
> 
> * Download the latest arm64 release
> * Build a docker image using the Dockerfile included in this repo?

I have downloaded release build from this repository.
Also I have build the file using commands from gitlab ci.
Afterwards I build Dockerfile which picks up existing binary.
In both cases it won't run on Raspberry Pi.

Dockerfile need to be fixed by using /usr/bin/SteamPrefill instead of /SteamPrefill

**Comment by tpill90** [comment] 2022-12-22 17:57
Made the change in #245

**Comment by tpill90** [comment] 2023-01-15 23:31
Released in [v1.9.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v1.9.0)

**Closed by tpill90** 2023-01-15 23:31 UTC
Labels: pending release
